# Site settings
title: SrÄ‘an on iOS & Swift
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "http://dev.srdanstanic.com"
repository: "srstanic/srstanic.github.io.git"
# Build settings
kramdown:
  input: GFM
permalink: /:slug/

# Third-party services
# just leave empty to disable it
google_analytics: UA-91990229-1
disqus_shortname: dev-srdanstanic-com

plugins:
  - jekyll-redirect-from